---
title: "Final Project"
author: "Nandagopal Panicker"
output: html_notebook
---


## Research Objective 

The aim of this project is to successfully compare two datasets to derive valuable insights from both of them. I have a couple of objectives in mind with regards to spotting trends:

* I want to find the top 5 artists in 2023 and 2024 respectively and make a vizualization revolving around the same.

* Since this is not a key feature in the 2024 dataset, I want to see if the bpm of a song has a correlation of sorts to how popular it is on the most popular streaming platform(Spotify).

* In addition to this, I want to compare the streams for songs over Spotify, Deezer, and Apple Music and see if the music in 2024 is more popular than the music in 2023.


## Data Processing 

#### Data Intake 

Include R code and a written explanation to import your **TWO** data sets.

#### Data Wrangling 

Include R code and written explanation for wangling your data (you can make multiple wrangled data sets). 




## Data Visualization

Include R code and written explanation for your data visualization(s) with at least 3 variables. You must have **at least** one graph. You may have more than one (I would encourage you to have more than one). 




## Conclusion

Answer your research question using the data sets and visualizations you created. 
